### ISSUE TITLE
Alternative URL for embedded dynamic maps

### ISSUE THREAD

**Issue by ulric-wilson** [jncc/jncc-website#35]
Project code
For time recording please use P0350 MPA Data Access and Management.

Some pages in current JNCC website have an embedded map that is also hyperlinked to the mapper page with the same view/layers selected - see http://jncc.defra.gov.uk/page-6536  and a similar requirement will be needed on new JNCC website.  Ultimately, this will come from Geoserver when the new MPA mapper is deployed but there will be a period when the new JNCC website in Umbraco is live and the old MPA mapper (set up by Felix as a standalone website) will be embedded in an iframe.

- can the embedded maps be maintained by pointing the img src to the 'standalone' mapper instead of the current example of http://jncc.defra.gov.uk/plugins/MPSMapper/proxyhandler.ashx?mapInstance=MPSMap_&LAYERS=World%2CTwelveTS%2CUKCS%2CReef%2CSandyRange%2CSAC&FORMAT=image%2Fpng&TRANSPARENT=true&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&SRS=EPSG%3A900913&BBOX=26187.113485579,6992552.3357379,121580.5247722,7081066.4144799&WIDTH=624&HEIGHT=579   [Yes they can]

- Can the functionality to hyperlink the above image to the Umbraco mapper iframe page, with preset map view and active layers,  be maintained - i.e. can the iframe be populated with a specific map based on querystring parameters.  (Question for Carbon 6)?  [yes possible  - may need tweaks from EMODnet iframe to be duplicated.]

### Tasks
- [x] set up ows.jncc.gov.uk
- [x]  UW contact C6 to fix iframe resizing
- [x] UW contact C6 to get javascript applied to iframe template as per EMODnet to fix 'permalink' domain issue
- [x] set up https for ows.jncc.gov.uk
- [ ] set up robots.txt file for https://mapper.mpa.jncc.gov.uk/

**Comment by felixMasonJncc** [comment]
WRT your first question - yes. The only changes to the code were styling changes. The proxy handler remains unafected. Eg this would work from the emodnet site:

	<img src="https://mapper.emodnet-seabedhabitats.eu/proxyhandler.ashx?mapInstance=MESHAtlanticMap_&LAYERS=EUSMCONF%2CEUSM2016&FORMAT=image%2Fpng&TRANSPARENT=true&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&SRS=EPSG%3A900913&BBOX=-5213589.6467119,3950705.1088489,4311075.5721413,9799055.0159566&WIDTH=1947&HEIGHT=1195">

**Comment by LynnHeeley** [comment]
-can embed image (Umbraco yes) - complete.
-load iframe with custom set of layers as part of request

**Comment by jonparsonsjncc** [comment]
liaise with Graeme Duncan - marine - to find out who to ask
are all instances of mapserver now ready to be served by geoserver

**Comment by jonparsonsjncc** [comment]
Meeting held with Graeme and Hugh

summary email below with outstanding tasks

Hi Hugh, Graeme

To summarise our discussion today and the tasks identified

Task - The current geo server is accessed through ows.emodnet-seabedhabitats.eu needs a new corporate, non-project specific URL creating
Action – The setup of https://ows.jncc.gov.uk has been requested, I will let you know timescales for this to be in place

Task – The new mapper.mpa.jncc.gov.uk system needs to be configured to use the new https://ows.jncc.gov.uk domain name to access the data
Action – Helen Woods, Marine Monitoring & Evidence team to action the changes

Task – The mapper.mpa.jncc.gov.uk system would benefit from a robots.txt file being added which will block search spiders from indexing the pages on the server
Action – Jon to discuss with Digital and Data team on how best to do this

Task – New iframe map page to be created on the http://edit-website (soon to be live version of the JNCC website) 
Action – Jon to create page and pass URL to Helen Woods, Marine Monitoring & Evidence team for creating the links to

Task – All pages requiring an embedded map image need to be identified
Action – Hugh, Graeme to review list of pages linked to from this category page http://edit-website/our-work/the-marine-protected-areas-category/ and inform Cathy Gardner of any missing pages

Task – Unique map image embed code and linking URL to iframe page (with parameters for specific options) to be created for each of the individual pages
Action - Helen Woods, Marine Monitoring & Evidence team to create the unique elements of code for each page

Task – Embed code to be content administered to each of the pages on the http://edit-website (soon to be live version of the JNCC website) 
Action – an administrator in the Marine Monitoring & Evidence team to add code to the pages and test the map image display and the link to the iframe page

Note:

The existing iframe page on the root of the beta site 
http://beta-website.jncc.gov.uk/resource-redirector/mpa-mapper/
can be passed a URL parameter in this format
http://beta-website.jncc.gov.uk/resource-redirector/mpa-mapper/?zoom=7&center=-4.826,54.559&layerIds=17,18,19&baseLayerId=-3&activeFilters=
to change the display of the map

I have also created another iframe this for the new mapper
http://beta-website.jncc.gov.uk/resource-redirector/mpa-mapper-new
Which can also be passed a parameter
http://beta-website.jncc.gov.uk/resource-redirector/mpa-mapper-new/?zoom=6&center=-3.814,48.240&layerIds=67,47&baseLayerId=-2&activeFilters=
but the new mapping system has an issue at present and doesn’t display layers correctly

Thanks both for your time in bringing me up to speed – much appreciated

Let me know how you get on with the tasks

Jon

**Comment by jonparsonsjncc** [comment]
Hi @ulric-wilson it would be good to confirm the location in the new JNCC website for iframe pages
My suggestion would be /iframe just to keep them tidy in one place and away from the root
Please advise

**Comment by jonparsonsjncc** [comment]
Hi @mattdebont 
Could you let me know if you are ok to create a robots txt file for this domain
https://mapper.mpa.jncc.gov.uk/
a help file here on best format
https://www.hostinger.co.uk/tutorials/website/how-to-block-search-engines-using-robotstxt

also could you advise if it is possible to add no index to the page
see below
https://support.google.com/webmasters/answer/93710?hl=en

thanks

**Comment by jonparsonsjncc** [comment]
Hi @ulric-wilson 
There are two issues highlighted by Graeme on the MPA mapper

"The iframe is spilling off the bottom of the page"
- presume he is looking for the iframe to lock to the bottom of the browser window or for the elements at the bottom of the map to move their position to always remain in the browser witndow - I am not sure if either of these are possible

"The permalink functionality isn’t working, as the permalink generates the link from the domain of the iframe content not the parent window. The “ifp” javascript fix implemented on the EMODnet Seabed Habitats Iframe page needs to be implemented here. Ulric and/or Paul should know what to do here I think."
- presume he is refering to this link in the map share option being different to the page URL - see attached - again not sure if this will be possible as the map is independent of the page
![image.png](https://images.zenhubusercontent.com/5cdad485818d2f78607e49ee/7f923275-47ea-476e-a997-42e1a0f4c3d8)

Could you please advise on action to take

thanks

**Comment by jonparsonsjncc** [comment]
Diagram of the whole process provided by Graeme

![MPA_dependencies (002).png](https://images.zenhubusercontent.com/5cdad485818d2f78607e49ee/d2df597a-0f9f-4b42-a0dd-f1dbec5dc4a0)
